# Generated by Django 3.0.7 on 2021-06-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpass', '0003_movementpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementpass',
            name='sub_dristrict',
        ),
    ]
