# Generated by Django 3.0.7 on 2021-06-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpass', '0004_remove_movementpass_sub_dristrict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementpass',
            name='move',
        ),
    ]
