# Generated by Django 3.0.7 on 2021-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpass', '0005_remove_movementpass_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Nid',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
