# Generated by Django 3.0.7 on 2021-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpass', '0007_passuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
