# Generated by Django 3.0.7 on 2021-07-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpass', '0008_profile_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassUser',
        ),
    ]
