export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const GET_ERRORS = 'GET_ERRORS';


export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const FETCH_USER_ALL_MOVEMENT_PASS = 'FETCH_USER_ALL_MOVEMENT_PASS';
export const FETCH_USER_MOVEMENT_PASS = 'FETCH_USER_MOVEMENT_PASS';

export const GET_USER = 'GET_USER';

export const FETCH_ADMIN_DASHBOARD = 'FETCH_ADMIN_DASHBOARD';
export const FETCH_RECENT_USERS = 'FETCH_RECENT_USERS';
export const FETCH_RECENT_PASS = 'FETCH_RECENT_PASS';
export const FETCH_All_PASS = 'FETCH_All_PASS';
export const FETCH_All_APPROVED_PASS = 'FETCH_All_APPROVED_PASS';
export const FETCH_All_PENDING_PASS = 'FETCH_All_PENDING_PASS';
export const FETCH_All_EXPIRED_PASS = 'FETCH_All_EXPIRED_PASS';

export const ADMIN_FETCH_All_USER = 'ADMIN_FETCH_All_USER';

export const APPROVE_USER_PASS = 'APPROVE_USER_PASS';
export const FETCH_SPECIFIC_USER = 'FETCH_SPECIFIC_USER';
export const FETCH_SPECIFIC_USER_PASS = 'FETCH_SPECIFIC_USER_PASS';